[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "house-price-predictor-industrialization"
version = "0.1.0"
description = "Industrialized house price prediction pipeline"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "scikit-learn==1.6.1",
    "house-price-predictor-shared",
]

[tool.setuptools]
packages = []

[tool.uv.sources]
house-price-predictor-shared = { path = "../shared", editable = true }
